### ISSUE TITLE
Fail to build in phone 

### ISSUE THREAD

**Issue by mtambo07** [Neogoma/Navigation-Tutorial-Demo#14]
I have tried to use demo to create an indoor navigation app but during build fail to build in my Android phone

**Comment by handrianj** [comment]
Hi, please tell us what version of unity are you using, what is the error in the build log?

**Comment by handrianj** [comment]
> I have tried to use demo to create an indoor navigation app but during build fail to build in my Android phone

Can you provide us with error logs and the unity version used ? We just tried building and it builds properly with 2022.2.19

**Comment by mtambo07** [comment]
![error log](https://github.com/Neogoma/Navigation-Tutorial-Demo/assets/129031061/2bdac63a-5771-47d6-9181-4530e4026623)

**Comment by mtambo07** [comment]
![error log 2](https://github.com/Neogoma/Navigation-Tutorial-Demo/assets/129031061/435c3810-8e3e-4743-bba7-fd6f071abf98)

**Comment by handrianj** [comment]
Your version of unity is not compatible with ARFoundation 5 that is used in the projects:

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/project-setup/install-arfoundation.html

"AR Foundation 5.0 is compatible with Unity 2021.2 and up."

**Comment by mahalakshmipp28** [comment]
I'm able to build and run the project but the images, materials, textures are not appearing on my phone when I try running the apk file. I have used Unity version 2022.2.19f1. The robot is not appearing on my phone in order to navigate. Only the camera is getting turned on. And also, the images are not visible in the scenes section.

**Comment by mahalakshmipp28** [comment]
Could not create asset from Assets/Neogoma/stardust-sdk/Material/arrow.png: File could not be read
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Could not create asset from Assets/Neogoma/stardust-sdk/Textures/loading.png: File could not be read
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

I'm getting this sort of errors when I tried opening any of the images in the file.

**Comment by mahalakshmipp28** [comment]
I have watched the 'AR navigation Tutorial using Stardust SDK' video in youtube. I just wished to try it out for my project, but then where is the 'CustomPathRenderer.cs' file located in the zip file that you have uploaded in your GitHub page?
