### ISSUE TITLE
How to add only location Targets, and not the Robot

### ISSUE THREAD

**Issue by CyberKrish2210** [Neogoma/Navigation-Tutorial-Demo#15]
So I want to just add Location Targets like google maps, so for example: I am building this app for my college building, and I want to locate all the places from the building. 
So What I want to do is, just show location targets. If a student walks to a classroom then the target should return the text (This is Classroom), rather than the robot.
There should be an option of (Select Destination), and if user wants to go to a specific location, then only the robot thing will pop up.
I also have many other questions, I'll ask the questions after this gets answered.

**Comment by handrianj** [comment]
Hi, so actually these questions are not related to the navigation system but a custom user experience system.

You can get rid of the robot, display prefabs at each target position, and use triggers/colliders to detect when the user is in the classroom.

Again it's not linked to the SDK nor a bug in the system so I will close this issue. Feel free to open the discussion on our discord server [here](https://discord.gg/2GkjF4x4)
